name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  packages: write

jobs:
  bake:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/bake-action@v3
        with:
          push: true